# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grasshopper
email: jeremyll33@yahoo.com
description: A blog mixing lawn care, libertarianism, life in Germany, nutrition and Taoism
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate: 3

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Jeremy Stocks
      layout: "post"
      category: general
      comments: true


