# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Baff
email: jeremyll33@yahoo.com
description: A blog mixing family life in Germany and BANTER!
baseurl: '/baff' # the subpath of your site
url: "http://jeremystocks.github.io/" # the base hostname & protocol for your site
paginate: 3

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Jeremy Stocks
      layout: "post"
      category: general
      comments: true


